name: Build Packages

on:
  push:
    paths:
      - 'debs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dpkg-scanpackages
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Generate Packages file
        run: |
          dpkg-scanpackages ./debs /dev/null > Packages
          gzip -k -f Packages

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Packages Packages.gz
          git commit -m "Auto update Packages" || echo "No changes to commit"
          git push
