jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dpkg-scanpackages
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Generate Packages file
        run: |
          cd debs
          dpkg-scanpackages . /dev/null > Packages
          gzip -k -f Packages

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add debs/Packages debs/Packages.gz
          git commit -m "Auto update Packages" || echo "No changes to commit"
          git push https://github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
